### ISSUE TITLE
cpanel warning

### ISSUE THREAD

**Issue by banglarsare** [cleonixtechnologies/Banglarsare#10]
Disk quota notification for “banglar2”.

The user “banglar2” (banglarsare.com) has reached their disk quota.

The account is currently 104.94% (10493.58/10000.00 megabytes) of its capacity.

Please remove some files from this account, or ask the system administrator to
increase the account’s disk quota.

!! Do not respond to this message. Your reply will go nowhere. !!

This notice was generated on “Saturday, March 5, 2016” at “10:14:28 AM UTC”.

[IMAGE]

Copyright© 2016 cPanel, Inc.

**Comment by debdiproy** [comment]
Please donot worry about this we moniter this
