### ISSUE TITLE
SEO report

### ISSUE THREAD

**Issue by banglarsare** [cleonixtechnologies/Banglarsare#12]
Sagar
Plz provide the current SEO report.

**Comment by Sagarjit** [comment]
I will send you the SEO report end of this week by email.

**Comment by debdiproy** [comment]
Sagar Please attend to this you have not send any email to Mr Tarak Paul Last week.

**Comment by Sagarjit** [comment]
Report sent, kindly check email.

**Comment by banglarsare** [comment]
you have mentioned that "handloom sarees" position 3&4 but this is the existing position of the banglarsare inner page rank. Your target page is home page for "handloom sarees", So, plz give the position of home page of the keyword "handloom sarees"
