### ISSUE TITLE
updates of Handicraftsforu

### ISSUE THREAD

**Issue by banglarsare** [cleonixtechnologies/Banglarsare#13]
What is the current status of handicraftsforu.com & handicraftsforu.in? When it will be ready to live?

**Comment by bikash02** [comment]
I have updated the below points for the  handicraftsforu.com & handicraftsforu.in
1.update top navigation 
2.category name
3.update the footer partly.

Please check from your end and let me know the further changes.
1.What to do regarding the website logo.
We will update the banner and category images by tomorrow. 

Thank you for cooperation..

**Comment by banglarsare** [comment]
At present handicrafts will be in samarkan font as logo is not ready from my end. When you ready the other pages.

**Comment by bikash02** [comment]
logo updated..

**Comment by banglarsare** [comment]
eta kono update holo........baki page gulor ki korli?
