### ISSUE TITLE
banglarsare.com backoffice not opening properly

### ISSUE THREAD

**Issue by banglarsare** [cleonixtechnologies/Banglarsare#15]
From today morning banglarsare backoffice not opening properly & when cliking to any option showing error. webmail also not opening. download the error screen shot.
[error.docx](https://github.com/cleonixtechnologies/Banglarsare/files/164822/error.docx)

**Comment by bikash02** [comment]
Its working..
![screenshot-www banglarsare com 2016-03-09 15-41-35](https://cloud.githubusercontent.com/assets/16361011/13631996/8044f628-e60d-11e5-8e13-e5b8129cc67d.png)

**Comment by bikash02** [comment]
![webmail](https://cloud.githubusercontent.com/assets/16361011/13632066/f8bc9dd6-e60d-11e5-8844-d00546b14f2f.png)
