### ISSUE TITLE
seo report

### ISSUE THREAD

**Issue by banglarsare** [cleonixtechnologies/Banglarsare#22]
Sagarjit,
you have mentioned that "handloom sarees" position 3&4 but this is the existing position of the banglarsare inner page rank. Your target page is home page for "handloom sarees", So, plz give the position of home page of the keyword "handloom sarees"

**Comment by Sagarjit** [comment]
The home page is exists in 4th position and the inner page is not in the same position before. When we do SEO for a website it is always every page get effected for the same.
