### ISSUE TITLE
Changes

### ISSUE THREAD

**Issue by debdiproy** [cleonixtechnologies/Banglarsare#27]
Remove add tag from product deatils page

Remove SSL Logo

Remove Middle name and address 1 field

Check account login and lougout and new account registration

Remove back to school from tank you page

Quantity and buy now shoud be under price and PIN

COD under Buy now button

Whats app number in the footer after phone number 9830960361

**Comment by bikash02** [comment]
Updated the below points.

Remove add tag from product deatils page
Remove SSL Logo
Remove Middle name and address 1 field
Remove back to school from tank you page
Quantity and buy now shoud be under price and PIN
Whats app number in the footer after phone number 9830960361
