### ISSUE TITLE
Changes

### ISSUE THREAD

**Issue by debdiproy** [cleonixtechnologies/Banglarsare#29]
1. In Product description page make the buy now section move up-word and social media section just below that. Adjust spacing.
2. Add the .com and .in icon in the Handicrafts 4 you logo
3. Check all the sites and create banners and promo banners necessary.

**Comment by Designer-cleonix** [comment]
![logo-com](https://cloud.githubusercontent.com/assets/16381310/14634492/ccb33b94-063f-11e6-845a-bacba247f7d2.png)
![logo-f-com](https://cloud.githubusercontent.com/assets/16381310/14634495/ccbb2bf6-063f-11e6-8a19-5a355640914c.png)
![logo-f-in](https://cloud.githubusercontent.com/assets/16381310/14634493/ccb7150c-063f-11e6-9913-8f8b9b541c96.png)
![logo-in](https://cloud.githubusercontent.com/assets/16381310/14634494/ccb8b434-063f-11e6-8294-8845b1c227ca.png)

**Comment by bikash02** [comment]
updated the logos in the live server.

**Comment by Designer-cleonix** [comment]
![banner-silk-sarees1](https://cloud.githubusercontent.com/assets/16381310/14637443/eb4f9d7c-064e-11e6-8aec-108440eb3cf4.jpg)
![banner-silk-sarees2](https://cloud.githubusercontent.com/assets/16381310/14637444/eb5056cc-064e-11e6-84fb-1f17ffce3d63.jpg)
![logo-com](https://cloud.githubusercontent.com/assets/16381310/14637446/eb512002-064e-11e6-98c5-16541bec310d.png)
![logo-in](https://cloud.githubusercontent.com/assets/16381310/14637445/eb5061e4-064e-11e6-92ff-b6f749b46426.png)

**Comment by Designer-cleonix** [comment]
Point 1 and Point 2 : Done
Point 3: Have done some works, remaining work will be done in two-days.

**Comment by banglarsare** [comment]
Debarati,
all the banners & logo are good. Plz make some banner for banglarsare.com &
.in. Also request you to change all the picture of banglarsare.com home
page category photo. Plz also check the size of photo for loading time.

Thanks

Tarak Paul

On Tue, Apr 19, 2016 at 4:53 PM, Debarati Bose Roy <notifications@github.com

**Comment by bikash02** [comment]
updated logo and banner images.
http://www.silksareez.com/
http://www.silksareez.in/

**Comment by Designer-cleonix** [comment]
Updated three category images. please send me pics of models  with handloom and cotton saree. i do not have the images.

**Comment by banglarsare** [comment]
plz download the picture for category handloom sarees, cotton sarees,
boutique sarees, silk sarees

On Wed, Apr 20, 2016 at 5:34 PM, Debarati Bose Roy <notifications@github.com
