### ISSUE TITLE
banner update

### ISSUE THREAD

**Issue by banglarsare** [cleonixtechnologies/Banglarsare#6]
plz update the category banner for banglarsare.in

![silk](https://cloud.githubusercontent.com/assets/17544314/13459526/475d6282-e09a-11e5-97b3-d87e2328e2b1.jpg)
![boutique](https://cloud.githubusercontent.com/assets/17544314/13459531/4da75c42-e09a-11e5-89cd-f7d14ac567c5.jpg)
![jamdani](https://cloud.githubusercontent.com/assets/17544314/13459535/5497b600-e09a-11e5-831b-bc88b62e7a8f.jpg)
![maheshwari](https://cloud.githubusercontent.com/assets/17544314/13459546/6d5f9e28-e09a-11e5-9d37-7bc1eb317524.jpg)

**Comment by Designer-cleonix** [comment]
Please give  names of the sarees @banglarsare .

**Comment by banglarsare** [comment]
plz follow the picture name, I have saved the picture as per the product category. Anyway maroon with multi colour saree for category "maheshwari Saree", White & red saree for "Jamdani saree" category, white & multi colour saree for "boutique saree", white & red border saree for "silk saree" category

all the picture for banglarsare.in category
